# Generated by Django 4.2.17 on 2025-06-13 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrtoken',
            name='expires_at',
        ),
        migrations.AlterField(
            model_name='qrtoken',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='qrtoken',
            name='token',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
