# Generated by Django 4.2.17 on 2025-06-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_company_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='daily_work_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4),
        ),
    ]
