# Generated by Django 4.2.17 on 2025-06-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_company_daily_work_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='added_by_hr',
            field=models.BooleanField(default=False),
        ),
    ]
