# Generated by Django 4.2.17 on 2025-07-01 12:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alter_attendance_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftsession',
            options={'ordering': ['-date', '-start_time'], 'verbose_name': 'Vardiya Kaydı', 'verbose_name_plural': 'Vardiya Kayıtları'},
        ),
        migrations.RemoveField(
            model_name='shiftsession',
            name='employee',
        ),
        migrations.AddField(
            model_name='shiftsession',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Şirket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiftsession',
            name='date',
            field=models.DateField(default=datetime.date(2025, 7, 1), help_text='Vardiyanın başladığı tarih (16:00-00:30 gibi durumlar için)', verbose_name='Vardiya Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiftsession',
            name='is_overnight',
            field=models.BooleanField(default=False, help_text='Ertesi güne sarkan vardiyalar için', verbose_name='Gece Vardiyası'),
        ),
        migrations.AddField(
            model_name='shiftsession',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notlar'),
        ),
        migrations.AddField(
            model_name='shiftsession',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shift_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shiftsession',
            name='auto_closed',
            field=models.BooleanField(default=False, help_text='Sistem tarafından kapatılan vardiyalar', verbose_name='Otomatik Kapatıldı'),
        ),
        migrations.AlterField(
            model_name='shiftsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Saati'),
        ),
        migrations.AlterField(
            model_name='shiftsession',
            name='start_time',
            field=models.DateTimeField(verbose_name='Başlangıç Saati'),
        ),
        migrations.AddIndex(
            model_name='shiftsession',
            index=models.Index(fields=['user', 'date'], name='core_shifts_user_id_4e2e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftsession',
            index=models.Index(fields=['is_overnight'], name='core_shifts_is_over_691556_idx'),
        ),
    ]
