# Generated by Django 4.2.17 on 2025-07-05 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_leaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('day', models.CharField(choices=[('mon', 'Pazartesi'), ('tue', 'Salı'), ('wed', 'Çarşamba'), ('thu', 'Perşembe'), ('fri', 'Cuma'), ('sat', 'Cumartesi'), ('sun', 'Pazar')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'ordering': ['week_start', 'day'],
                'unique_together': {('employee', 'week_start', 'day')},
            },
        ),
    ]
