# Generated by Django 4.2.17 on 2025-07-05 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_weeklyschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Pazartesi'), ('tue', 'Salı'), ('wed', 'Çarşamba'), ('thu', 'Perşembe'), ('fri', 'Cuma'), ('sat', 'Cumartesi'), ('sun', 'Pazar')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('week_start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='employee_schedules', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(limit_choices_to={'role__in': ['company_owner', 'hr']}, on_delete=django.db.models.deletion.CASCADE, related_name='manager_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Çalışma Planı',
                'verbose_name_plural': 'Çalışma Planları',
                'ordering': ['week_start_date', 'day', 'employee'],
                'unique_together': {('employee', 'day', 'week_start_date')},
            },
        ),
        migrations.DeleteModel(
            name='WeeklySchedule',
        ),
    ]
